### ISSUE TITLE
Guide for Installation on Ubuntu 20.10 on Raspberry Pi 4 with Extras!

### ISSUE THREAD

**Issue by MarkProminic** [balena-os/wifi-connect#392]
This guide is to document how I was able to install the Wifi-connect and Wifi-connect-api  using Docker on my Raspberry Pi installed with Ubuntu 20.10 (following the ZFS Guide: [Ubuntu 20.10 root on ZFS for Raspberry Pi](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS%20for%20Raspberry%20Pi.html#step-1-disk-formatting)

### Installations Steps

Step 1. Install Ubuntu Per the Guide above or via the Standard Noobs Installation

Step 2. Install [Docker](https://docs.docker.com/engine/install/ubuntu/) and [Docker Compose](https://docs.docker.com/compose/install/) for Raspberry Pi 64 (aarch64)

Step 3. Since I wanted this to be in my existing Docker Swarm/Cluster, I Added the Following Docker-Compose Configuration to docker-compose.yaml.

Note the important parts here are to Give this container Priveleged Access, Host Network, and to define the DBUS connection as it is different in Ubuntu than BalenaOS:

```
---
version: "3.9"
services:
  ~~~~ Other Services Here
  wifi-connect-api:
    build:
      context: "wifi-connect-api"
      dockerfile: Dockerfile-wifi-connect-api
    image: result/latest
    network_mode: host
    privileged: true
## I am not sure how Labels work as I am new to Docker, I don't think these apply without the Balena Superviosor. Someone please correct me
    labels: 
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    volumes:
    - "path/to/{ui_and_web-app.py}:/usr/src/app/"
    - type: bind
      source: /dev/bus/usb
      target: /dev/bus/usb
    - type: bind
      source: /var/run/dbus
      target: /var/run/dbus

```
Step 4. Download the Requirements and made my Adjustments to the Scripts, UI, etc:

```
git clone https://github.com/balena-io-examples/wifi-connect-api
```
Step 5. I Modified the Dockerfile that the Docker Compose kicks off to: Dockerfile-wifi-connect-api:

```
FROM balenalib/raspberrypi4-64-python
RUN install_packages dnsmasq curl
ENV WIFI_CONNECT_VERSION v4.2.5
WORKDIR /tmp/download
RUN curl -Ls https://github.com/balena-os/wifi-connect/releases/download/v4.4.5/wifi-connect-v4.4.5-linux-aarch64.tar.gz \
    | tar -xvz -C /tmp/download
RUN mv wifi-connect /usr/local/sbin
RUN rm -rdf /tmp/download
WORKDIR /usr/src/app
RUN pip install --upgrade pip
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY . ./
ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/var/run/dbus/system_bus_socket
CMD ["python", "web-app.py"]
```

Step 6. Run Docker Build:

```
docker-compose build --no-cache
```
Step 7. Run Docker Up to start the instance to test:

```
docker-compose up -d
```
Step 8. Verify that Wifi-Connect Launches, You can connect, it sticks, no issues occur, Etc

### Congratulations! The Docker container runs! Here are the Extras!

But how do I get a Secured Connections if I redirect? Well you can Preload a Certificate using Nginx or HAproxy.

What if I want to embed the Wifi Connect page in an site? Nginx and HAproxy also have the ability to handle this. Though configs can get tricky.

Step 9. Setup Haproxy/Nginx on your Raspberry Pi as a Reverse Proxy:

Nginx and Haproxy Install
```
apt-get install haproxy nginx -y
```

Haproxy Config

```
```

Step 10. Adjust the code in the Sample Script to point 

### Even More Extra's and Goodies

What if I want the Device to Dynamic Update it's FQDN?

Well, I have made a small bash script and followed the following Guide to setup a External DDNS server using Bind9 on Ubuntu 20.10. There are quiet a few difference in the bind that they used in their version, but the gist is there and it works perfectly. 

Step 11. 

Server Side:  
> [DDNS Guide](https://suoranciata.github.io/self-hosted-dynamic-dns-named-nginx-openresty.html)

Client Side: 
Example Bash script, call using rc.local, systemd, cron or some other method of your choosing:
> `Register.sh` (rename from .txt) -- [register.txt](https://github.com/balena-os/wifi-connect/files/6271631/register.txt)

I have sanitized and stripped this down, so you will need to replace  domains, paths, usernames, etc.  but you can adjust the Sed commands to modify the web-app.py file that you mounted via a volume instead of having it read only on the Docker File System.

Sources:

- Web-App.py -- Example Code -- https://github.com/balena-io-examples/wifi-connect-api
- ZoL - Ubuntu - RPi 4 -- https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS%20for%20Raspberry%20Pi.html#step-1-disk-formatting
- OpenResty -- Open Source API -- https://blog.openresty.com/en/ubuntu20-or-install/
- Docker -- https://docs.docker.com/engine/install/ubuntu/
- Docker-Compose (PIP3) -- https://docs.docker.com/compose/install/
- Wifi-Connect -- https://github.com/balenablocks/wifi-connect
- This Reddit Post -- https://www.reddit.com/r/homeassistant/comments/j5g4v2/i_got_bt_working_in_docker_only_took_hours/ and his subsequent [Free Software Servers](https://www.freesoftwareservers.com/display/FREES/Bluetooth+Scanning+with+Home-Assistant+in+Docker+in+a+VM)

Other Potentially Similar Issues:

- https://github.com/balena-os/wifi-connect/issues/238
- https://github.com/balena-os/wifi-connect/issues/222
- https://github.com/balena-os/wifi-connect/issues/352
- https://github.com/balena-os/wifi-connect/issues/121
